RCS/Controllers/AdvertisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using RCS.viewModels;
using RCS.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Configuration;
using RCS.Filters;
using PagedList;

namespace RCS.Controllers
{
    [Authorize]
    [expiredAdvs]
    public class AdvertisesController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AdvertisesController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        
        [AllowAnonymous]
        // GET: Products
        public ActionResult Index(int? page)
        {
            var prod = new List<allProduct>();
            foreach(var pro in _context.Products.Include(s=>s.Category).Where(x=>x.status == true).ToList())
            {
                var name = _context.images.First(c => c.productId == pro.id).ImagePath.Split('\\');
                var ins = new allProduct()
                {
                    id = pro.id,
                    name = pro.name,
                    catName = pro.Category.catName,
                    depName = pro.Category.Department.depName,
                    price = pro.price,
                    imagePath = name[name.Length - 1],
                };
                prod.Add(ins);
            };
            
            return View(prod.ToPagedList(page ?? 1,12));
        }
        public ActionResult makeAdvertise()
        {
            string userId = User.Identity.GetUserId();
            var Owner = _context.Users.FirstOrDefault(s => s.Id == userId);
            var viewmode = new productViewModel()
            {

                Departments = _context.Departments.ToList(),
                Categories = null,
                ownerName = Owner.UserName,
                ownerEmail = Owner.Email,
                ownerPhone = Owner.PhoneNumber
            };
            return View("AdvertiseForm", viewmode);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult save(productViewModel pvm)
        {
            string userId = User.Identity.GetUserId();
            var Owner = _context.Users.FirstOrDefault(s => s.Id == userId);
            if (pvm.ImageFile[0] != null)
            {
                string Extensions = "png,jpg,jpeg";
                List<string> allowedExtensions = Extensions.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList();
                for (int i = 0; i < pvm.ImageFile.Length; i++)
                {
                    if (!allowedExtensions.Any(y => pvm.ImageFile[i].FileName.EndsWith(y)) || pvm.ImageFile[i].ContentLength > 3145728 || pvm.price <= 0)
                    {
                        pvm.Departments = _context.Departments.ToList();
                        pvm.ownerName = Owner.UserName;
                        pvm.ownerEmail = Owner.Email;
                        pvm.ownerPhone = Owner.PhoneNumber;
                        return View("AdvertiseForm", pvm);
                    }
                }
            }
            var product = new Product();
            if (pvm.id == 0)
            {
                product.name = pvm.name;
                product.Category = _context.Categories.SingleOrDefault(x => x.id == pvm.CategoryID);
                product.catid = pvm.CategoryID;
                product.description = pvm.description;
                product.address = pvm.address;
                product.price = pvm.price;
                product.ownerId = userId;
                product.status = false;
                product.DateAdded = null;
                _context.Products.Add(product);
            }
            else
            {
               
                product =  _context.Products.Single(x=>x.id == pvm.id);
                product.name = pvm.name;
                product.Category = _context.Categories.SingleOrDefault(x => x.id == pvm.CategoryID);
                product.catid = pvm.CategoryID;
                product.description = pvm.description;
                product.address = pvm.address;
                product.price = pvm.price;
                product.ownerId = userId;
                product.status = false;
                product.DateAdded = null;
                if (pvm.ImageFile[0] != null)
                {
                    var images = _context.images.Where(x => x.productId == pvm.id).ToList();
                    for (int i = 0; i < images.Count; i++)
                    {
                        if (System.IO.File.Exists(images[i].ImagePath))
                        {
                            System.IO.File.Delete(images[i].ImagePath);
                            _context.images.Remove(images[i]);
                        }
                    }
                }
                            
                
           }

        if (pvm.ImageFile[0] != null)
        {
            for (int i = 0; i < pvm.ImageFile.Length; i++)
            {
                string FileName = Path.GetFileNameWithoutExtension(pvm.ImageFile[i].FileName);
                string FileExtension = Path.GetExtension(pvm.ImageFile[i].FileName);
                var count = i + 1;
                FileName = DateTime.Now.ToString("yyyyMMdd") + "-" + pvm.name + "-" + count + FileExtension;
                string UploadPath = ConfigurationManager.AppSettings["UserImagePath"].ToString();
                pvm.ImagePath = UploadPath + FileName;
                pvm.ImageFile[i].SaveAs(pvm.ImagePath);
                var image = new images();
                image.ImagePath = pvm.ImagePath;
                image.productId = product.id;
                _context.images.Add(image);
            }
        }
            
               
            

                _context.SaveChanges();
            return RedirectToAction("myAdvertises");
        }
        public ActionResult showDetails(int? id)
        {
          
            try
            {
                
                var pro = _context.Products.Include(x=>x.owner).Single(x => x.id == id);
                var product = new detailsViewModel()
                {
                    id = pro.id,
                    productname = pro.name,
                    address = pro.address,
                    catName = pro.Category.catName,
                    depName = pro.Category.Department.depName,
                    description = pro.description,
                    price = pro.price,
                    owner = pro.owner,
                    imagePath = new List<string>(),
                    state = pro.status,
                };

                var imagesPath = _context.images.Where(x => x.productId == pro.id).Select(x => x.ImagePath).ToList();

                for (int i = 0; i < imagesPath.Count; i++)
                {
                    var file_name = imagesPath[i].Split('\\');
                    product.imagePath.Add(file_name[file_name.Length - 1]);
                }
                if (User.IsInRole("Admin") && pro.status == false)
                {
                    return View(product);
                }
                else if (pro.status == false)
                {
                    return RedirectToAction("index");
                }
                return View(product);
            }
            catch
            {
                return RedirectToAction("index");
            }
        }
        
        public ActionResult Edit(int id)
        {
            string userId = User.Identity.GetUserId();
            var Owner = _context.Users.FirstOrDefault(s => s.Id == userId);
            var product = new Product();
            product = _context.Products.Include(s=>s.Category).Single(i => i.id == id);
            var viewmodel = new productViewModel()
            {
                id = product.id,
                name = product.name,
                price = product.price,
                ownerEmail = Owner.Email,
                ownerName = Owner.UserName,
                ownerPhone = Owner.PhoneNumber,
                address = product.address,
                CategoryID = product.catid,
                DepartmentID = product.Category.depId,
                Categories = null,
                Departments = _context.Departments.ToList(),
                description = product.description,
                
            };
            return View("AdvertiseForm", viewmodel);
        }
        public ActionResult myAdvertises()
        {
            return View();
        }
    }
}

RCS/Views/Advertises/AdvertiseForm.cshtml
@model RCS.viewModels.productViewModel
@{
    ViewBag.Title = RCS.Resources.Resource.MakeRequest;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ 
    var check = (Model.id == 0) ? "required" : "";
}
<div class="addproductPage wow fadeIn container p-4 border col-md-8" style="margin-top: 200px;">
    @using (Html.BeginForm("save", "Advertises", FormMethod.Post, new { @class = "p-4", role = "form" , id="add" , enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken();
        <p class="text-primary @RCS.Resources.Resource.text">@RCS.Resources.Resource.ProductInfo</p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <hr>
        <div class="form-group row">
            <div class="col-sm-10">
                @Html.HiddenFor(m => m.id, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.name, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.name, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.name, "", new { @class = "text-danger " })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.DepartmentID, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.DropDownListFor(m=>m.DepartmentID, new SelectList(Model.Departments, "id", "depName"), "Choose Department", htmlAttributes: new { @class = "form-control form-control-sm" })
                @Html.ValidationMessageFor(m => m.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.CategoryID, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                <select class="form-control form-control-sm" id="CategoryID" name="CategoryID" required>
                    <option value>Choose Category</option>
                </select>
                @Html.ValidationMessageFor(m => m.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.description, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextAreaFor(m => m.description, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.ImagePath, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div id="InputImage" class="ml-5 mb-5">
                <div class="row">
                    <input type="file" id="ImageFile" name="ImageFile" multiple  @check>
                    @Html.ValidationMessageFor(m => m.ImageFile, "", new { @class = "text-danger" })
                </div>
                <div class="row">
                    <p class="text-info">@RCS.Resources.Resource.imagesInq</p>
                    <div id="imgs"></div>
                </div>
            </div>
            
            <!--
            <div class="col-sm-10">
                <button id="addimage" class="btn btn-outline-primary float-right" onclick="Generate(event)" role="button">Add Another Images</button>
            </div>
                -->
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.address, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextAreaFor(m => m.address, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.price, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-2">
                @Html.TextBoxFor(m => m.price, htmlAttributes: new { @class = "form-control col-sm-10", type = "number" })
                @Html.ValidationMessageFor(m => m.price, "", new { @class = "text-danger " })
            </div>
            <div class="col-sm-2">
                <span style="line-height: 36px;">EGP</span>
            </div>
        </div>
        <p class="text-primary @RCS.Resources.Resource.text">@RCS.Resources.Resource.OwnerInfo</p>
        <hr>
        <div class="form-group row">
            @Html.LabelFor(m => m.ownerName, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.ownerName, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.ownerPhone, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.ownerPhone, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.ownerEmail, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.ownerEmail, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group row ">
            @if (Model.id == 0)
            {
                <div class="col-sm-10">
                    <button type="submit" id="submit" class="btn btn-primary">@RCS.Resources.Resource.MakeRequest</button>
                </div>
            }
            else
            {
                <div class="col-sm-10">
                    <button type="submit" id="submit" class="btn btn-primary">@RCS.Resources.Resource.UpdateRequest</button>
                </div>
            }

        </div>
    }
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
<script>
        new WOW().init();
        $(document).ready(function () {

            $("#ImageFile").on("change", function () {
                console.log(this.files);

            });

            $("#DepartmentID").val();
            $.ajax({
                method: "GET",
                url: "http://localhost:54302/api/department/getCategory?depid=" + $("#DepartmentID").val(),
                success: function (data) {
                    $("#CategoryID").empty();
                    $("#CategoryID").append(`<option value>.....</option>`);
                    for (i = 0 ; i < data.length; i++) {
                        var elem = `<option value=${data[i].id}>${data[i].catName}</option>`;
                        $("#CategoryID").append(elem);
                    }
                    $("#CategoryID").val('@Model.CategoryID');
                },
                error: function () {
                    $("#CategoryID").empty();
                    $("#CategoryID").append(`<option value>Choose Category</option>`);
                },
            });

            $("#price").on("change", function () {
                if ($(this).val() < 0) {
                    $(this).val("0");
                }
            })

            $("#DepartmentID").on("change", function () {
                $.ajax({
                    method:"GET",
                    url:"http://localhost:54302/api/department/getCategory?depid=" + $(this).val(),
                    success: function (data) {
                        $("#CategoryID").empty();
                        $("#CategoryID").append(`<option value>.....</option>`);
                        for (i = 0 ; i < data.length; i++) {
                            var elem = `<option value=${data[i].id}>${data[i].catName}</option>`;
                            $("#CategoryID").append(elem);
                        }
                    },
                    error: function () {
                        $("#CategoryID").empty();
                        $("#CategoryID").append(`<option value>Choose Category</option>`);
                    },
                });
            })
        })
</script>    
    
}

RCS/Views/Advertises/Index.cshtml
@using Microsoft.AspNet.Identity;
@model IPagedList<RCS.viewModels.allProduct>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = RCS.Resources.Resource.Advertises;
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<div class="category container">
    <h2 class="wow bounceIn pb-1 border-bottom font-weight-bold @RCS.Resources.Resource.text">@RCS.Resources.Resource.AllAdvertises</h2>
    @if (Request.IsAuthenticated && !User.IsInRole("Admin"))
    {
        <div class="row justify-content-center">
            <a href="~/Advertises/makeAdvertise" class="btn btn-primary wow tada">@RCS.Resources.Resource.MakeAdvertise</a>
        </div>}
    <div class="row" align="center">
        <form class="ml-4 col-md-12">
            <div class="form-group row col-md-12">
                <label for="Search" class="col-sm-1 col-form-label col-form-label-lg wow fadeIn">@RCS.Resources.Resource.Search</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control col-md-12 form-control-lg wow fadeIn" id="Search">
                </div>
            </div>
        </form>
    </div>
    <div id="filter" class="row justify-content-center p-2 wow fadeIn" align="center">
        <a href="/Advertises/index" id="all" class="dep btn btn-outline-danger mr-1 mt-1 active" data-dep="All">@RCS.Resources.Resource.All</a>
        <div class="dropdown">
            <button class="dep btn btn-outline-danger dropdown-toggle mr-1 mt-1" data-dep="Buy / Sell" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @RCS.Resources.Resource.BuySell
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Equipment">@RCS.Resources.Resource.Equipment</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Basics">@RCS.Resources.Resource.Basis</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Devices">@RCS.Resources.Resource.Devices</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Shops">@RCS.Resources.Resource.Shops</a>
            </div>
        </div>
        <div class="dropdown">
            <button class="dep btn btn-outline-danger dropdown-toggle mr-1 mt-1" data-dep="Services" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @RCS.Resources.Resource.Services
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Interior Design">@RCS.Resources.Resource.InteriorDesign</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Exterior Design">@RCS.Resources.Resource.ExteriorDesign</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Design and Print Menus">@RCS.Resources.Resource.DesignandPrintMenus</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Franchise Guide">@RCS.Resources.Resource.FranchiseGuide</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Create Brandings">@RCS.Resources.Resource.CreateBrandings</a>
            </div>
        </div>
        <div class="dropdown">
            <button class="dep btn btn-outline-danger dropdown-toggle mr-1 mt-1" data-dep="Jobs" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @RCS.Resources.Resource.Jobs
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Stewarts">@RCS.Resources.Resource.Stewarts</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Chiefs">@RCS.Resources.Resource.Chiefs</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Delivery">@RCS.Resources.Resource.Delivery</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Cleaners">@RCS.Resources.Resource.Cleaners</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Accountants">@RCS.Resources.Resource.Accountants</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Managers">@RCS.Resources.Resource.Managers</a>
            </div>
        </div>
        <div class="dropdown">
            <button class="dep btn btn-outline-danger dropdown-toggle mr-1 mt-1" data-dep=" News / Events" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @RCS.Resources.Resource.NewsEvents
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Local">@RCS.Resources.Resource.Local</a>
                <a class="dropdown-item cat @RCS.Resources.Resource.text" data-CateName="Global">@RCS.Resources.Resource.Global</a>
            </div>
        </div>
    </div>
</div>

<div class="products mb-4 mt-4 justify-content-center">
    <div class="row item justify-content-center ">
        @if (!Model.Any())
        {
            <h3 style="height:500px">@RCS.Resources.Resource.noAdvertise</h3>
        }
        else
        {
            foreach (var product in Model)
            {
                var dep = " ";
                var cat = " ";
                if (product.depName == "Buy / Sell") { dep = RCS.Resources.Resource.BuySell; }
                else if (product.depName == "Services") { dep = RCS.Resources.Resource.Services; }
                else if (product.depName == "Jobs") { dep = RCS.Resources.Resource.Jobs; }
                else if (product.depName == "News / Events") { dep = RCS.Resources.Resource.NewsEvents; }


                if (product.catName == "Equipment") { cat = RCS.Resources.Resource.Equipment; }
                else if (product.catName == "Basics") { cat = RCS.Resources.Resource.Basis; }
                else if (product.catName == "Devices") { cat = RCS.Resources.Resource.Devices; }
                else if (product.catName == "Shops") { cat = RCS.Resources.Resource.Shops; }
                else if (product.catName == "Interior Design") { cat = RCS.Resources.Resource.InteriorDesign; }
                else if (product.catName == "Exterior Design") { cat = RCS.Resources.Resource.ExteriorDesign; }
                else if (product.catName == "Design and Print Menues") { cat = RCS.Resources.Resource.DesignandPrintMenus; }
                else if (product.catName == "Franchise Guide") { cat = RCS.Resources.Resource.FranchiseGuide; }
                else if (product.catName == "Create Brandings") { cat = RCS.Resources.Resource.CreateBrandings; }
                else if (product.catName == "Stewarts") { cat = RCS.Resources.Resource.Stewarts; }
                else if (product.catName == "Chiefs") { cat = RCS.Resources.Resource.Chiefs; }
                else if (product.catName == "Delivery") { cat = RCS.Resources.Resource.Delivery; }
                else if (product.catName == "Cleaners") { cat = RCS.Resources.Resource.Cleaners; }
                else if (product.catName == "Accountants") { cat = RCS.Resources.Resource.Accountants; }
                else if (product.catName == "Managers") { cat = RCS.Resources.Resource.Managers; }
                else if (product.catName == "Local") { cat = RCS.Resources.Resource.Local; }
                else if (product.catName == "Global") { cat = RCS.Resources.Resource.Global; }


                <div class="p-2  wow bounceInUp" style="height:400px" data-CateName="@product.catName">
                    <img src="~/uploadedFiles/@product.imagePath">
                    <h6 class="p-1 mt-2">@product.name <span class="font-weight-bold float-right" style="font-size: 12px; line-height: 25px;">@product.price EGP</span></h6>

                    <span class="badge badge-primary p-1 " style="margin-top:8px">@dep</span>
                    <span class="badge badge-info p-1 ">@cat</span>
                    <a href="/Advertises/showDetails?id=@product.id" class="btn btn-danger float-right" role="button">@RCS.Resources.Resource.ShowDetails</a>
                </div>
            }
        }
    </div>
</div>

<h1></h1>

@Html.PagedListPager(Model, page => Url.Action("index", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })

@section scripts{
    <script>
        new WOW().init();
        $(document).ready(function () {
            $("nav .navbar-collapse ul li a:eq(1)").css("color", "#ff4301");
            $("#filter .cat").on("click", function () {
                $("#filter .dep").removeClass("active");
                $(this).parent().prev().toggleClass("active");
                $("#filter .cat").removeClass("active");
                $(this).toggleClass("active");
                let val = $(this).attr("data-CateName");
                $.ajax({
                    url: `/api/department/GetCatPro?catName=${val}`,
                    method: "GET",
                    beforeSend: function () {
                        $(".products .item").empty();
                    },
                    success: function (data) {
                        $(".pagination-container").removeClass(" d-flex");
                        $(".pagination-container").addClass(" d-none");

                        $(".products .item").empty();
                        if (data.length == 0) {
                            $(".products .item").append(`<h3 style="height: 500px">@RCS.Resources.Resource.noAdvertise</h3>`);
                        }
                        for (let i = 0; i < data.length; i++) {
                            var imageName = data[i].image.split("\\");
                            var elem = `
                                    <div class="p-2  " style="height:400px" data-CateName="${data[i].cat}">
                                        <img src="../uploadedFiles/${imageName[imageName.length - 1]}">
                                        <h6 class="p-1 mt-2"> ${data[i].nam} <span class="font-weight-bold float-right" style="font-size: 12px; line-height: 25px;">${data[i].price} EGP</span></h6>
                                        <span class="badge badge-primary p-1 " style="margin-top:8px">${data[i].dep}</span>
                                        <span class="badge badge-info p-1 ">${data[i].cat}</span>
                                        <a href="/Advertises/showDetails?id=${data[i].id}" class="btn btn-danger float-right" role="button">@RCS.Resources.Resource.ShowDetails</a>
                                    </div>`;

                            $(".products .item").append(elem);
                        }
                    }
                });
            });

            $(".pagination-container").addClass(" d-flex justify-content-center");
            $(".pagination li").addClass(" page-item");
            $(".pagination li a").addClass(" page-link");

            $("#Search").on("keyup", function () {
                var val = $(this).val();
                if (val != "") {
                    $.ajax({
                        url: `/api/Product?name=${val}`,
                        method: "GET",
                        beforeSend: function () {
                            $(".products .item").empty();
                        },
                        success: function (data) {
                            $(".pagination-container").removeClass(" d-flex");
                            $(".pagination-container").addClass(" d-none");

                            $(".products .item").empty();
                            if (data.length == 0) {
                                $(".products .item").append(`<h3 style="height: 500px">@RCS.Resources.Resource.noAdvertise</h3>`);
                            }
                            console.log(data);
                            for (let i = 0; i < data.length; i++) {
                                var imageName = data[i].image.split("\\");
                                var elem = `
                                    <div class="p-2  " style="height:400px" data-CateName="${data[i].cat}">
                                        <img src="../uploadedFiles/${imageName[imageName.length - 1]}">
                                        <h6 class="p-1 mt-2"> ${data[i].nam} <span class="font-weight-bold float-right" style="font-size: 12px; line-height: 25px;">${data[i].price} EGP</span></h6>
                                        <span class="badge badge-primary p-1 " style="margin-top:8px">${data[i].dep}</span>
                                        <span class="badge badge-info p-1 ">${data[i].cat}</span>
                                        <a href="/Advertises/showDetails?id=${data[i].id}" class="btn btn-danger float-right" role="button">@RCS.Resources.Resource.ShowDetails</a>
                                    </div>`;

                                $(".products .item").append(elem);
                            }
                        }
                    })
                }
                else {
                    window.location.reload();
                }
            });

        });
    </script>
}